#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh

export ZDOTDIR=$HOME/.config/zsh

# https://blog.patshead.com/2011/04/improve-your-oh-my-zsh-startup-time-maybe.html
skip_global_compinit=1

export SYSTEM=$(uname -s)
