tap "ublue-os/tap", trusted: true

brew "bat"
brew "biber"
brew "fd"
brew "fzf"
brew "glow"
brew "htop"
brew "jq"
brew "latexdiff"
brew "latexindent"
brew "lsd"
brew "media-info"
brew "neovim"
brew "pandoc"
brew "procs"
brew "pv"
brew "qpdf"
brew "rclone"
brew "restic"
brew "ripgrep"
brew "smartmontools"
brew "squashfs"
brew "starship"
brew "tesseract"
brew "tesseract-lang"
brew "tcpdump"
brew "tealdeer"
brew "texlive"
brew "tmux"
brew "ykman"
brew "zsh-autosuggestions"
brew "zsh-fast-syntax-highlighting"

cask "ublue-os/tap/visual-studio-code-linux", trusted: true
