type: rpm-ostree
install:
  - bat
  - fd-find
  - hddtemp
  - jq
  - lm_sensors
  - lsd
  - neovim
  - openssh
  - procinfo
  - procs # A modern replacement for ps
  - pv # A tool for monitoring the progress of data through a pipeline.
  - usermod
  - zsh
  - zsh-autosuggestions
  # - mailcap tree-sitter-cli wl-clipboard xdg-utils xsel # neovim weak deps: 13M (+ 27M =40M )
